Ledger/Controllers/IssueController.cs
using Ledger.DB;
using Ledger.DB.Models;
using Ledger.DB.VModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;

namespace Ledger.Controllers
{
    public class IssueController : Controller
    {
        private readonly ApplicationDB dbcontext;

        public IssueController(ApplicationDB db)
        {
            dbcontext = db;
        }
        public IActionResult Index()
        {
            ViewBag.Branch = dbcontext.Branch.ToList();
            ViewBag.Equipment = dbcontext.Equipment.ToList();

            List<VIssue> Issue = dbcontext.Issue
                .Where(i=>i.Status == true)
                .Select(i => new VIssue
            {
                Id = i.Id,
                EquipmentName = i.Equipment.Name,
                BranchName = i.Branch.Name,
                Condition = i.Condition,
                SerialNo = i.SerialNo,
                Qty = i.Qty,
                IssueVoucher = i.IssueVoucher,
                IssueTo = i.IssueTo,
                ReceviedBy = i.ReceviedBy

            }).ToList();
            return View(Issue);
        }

        [HttpPost]
        public IActionResult Create(Issue I)
        {
            Issue ID = new Issue();
            ID.EquipmentId = I.EquipmentId;
            ID.BranchId = I.BranchId;
            ID.Condition = I.Condition;
            ID.SerialNo = I.SerialNo;
            ID.Qty = I.Qty;
            ID.IssueDate = I.IssueDate;
            ID.IssueVoucher = I.IssueVoucher;
            ID.MinSheetNo = I.MinSheetNo;
            ID.IssueTo = I.IssueTo;
            ID.ReceviedBy = I.ReceviedBy;
            ID.Details = I.Details;
            ID.Status = true;
            ID.CreatedOn = DateTime.Now;
            ID.CreatedBy = "Aqib";
            ID.EditedOn = DateTime.Now;
            ID.EditedBy = "Aqib";
            dbcontext.Issue.Add(ID);
            dbcontext.SaveChanges();
            return Json("Success !!!");
        }

        [HttpPost]
        public IActionResult GetIssue(int Id)
        {
            var IssueData = dbcontext.Issue.Where(e => e.Id == Id && e.Status == true).FirstOrDefault();
            return Json(IssueData);
        }
          [HttpPost]
        public IActionResult GetDetail(int Id)
        {
            var IssueData = dbcontext.Issue.Where(e => e.Id == Id && e.Status == true).FirstOrDefault();
            var Issue = dbcontext.Issue
               .Where(i => i.Id == Id)
               .Select(i => new VIssue
               {
                   Id = i.Id,
                   EquipmentName = i.Equipment.Name,
                   BranchName = i.Branch.Name,
                   Condition = i.Condition,
                   SerialNo = i.SerialNo,
                   Qty = i.Qty,
                   IssueDate = i.IssueDate,
                   IssueVoucher = i.IssueVoucher,
                   MinSheetNo = i.MinSheetNo,
                   IssueTo = i.IssueTo,
                   ReceviedBy = i.ReceviedBy,
                   Details = i.Details,
                   CreatedBy = i.CreatedBy
               }).FirstOrDefault();
            return Json(Issue);
        }

         
       



        [HttpPost]
        public IActionResult Update(Issue I)
        {
            Issue ID = dbcontext.Issue.Where(i => i.Id == I.Id).FirstOrDefault();
            ID.BranchId = I.BranchId;
            ID.Condition = I.Condition;
            ID.SerialNo = I.SerialNo;
            ID.Qty = I.Qty;
            ID.IssueDate = I.IssueDate;
            ID.IssueVoucher = I.IssueVoucher;
            ID.MinSheetNo = I.MinSheetNo;
            ID.IssueTo = I.IssueTo;
            ID.ReceviedBy = I.ReceviedBy;
            ID.Details = I.Details;
            ID.Status = true;
           
            ID.EditedOn = DateTime.Now;
            ID.EditedBy = "Aqib";
            dbcontext.SaveChanges();
            return Json("Success !!!");
        }



        [HttpGet]
        public IActionResult PrintIssue(int Id)
        {
            var IssueData = dbcontext.Issue.Where(e => e.Id == Id && e.Status == true).FirstOrDefault();
            var Issue = dbcontext.Issue
               .Where(i => i.Id == Id)
               .Select(i => new VIssue
               {
                   Id = i.Id,
                   EquipmentName = i.Equipment.Name,
                   BranchName = i.Branch.Name,
                   Condition = i.Condition,
                   SerialNo = i.SerialNo,
                   Qty = i.Qty,
                   IssueDate = i.IssueDate,
                   IssueVoucher = i.IssueVoucher,
                   MinSheetNo = i.MinSheetNo,
                   IssueTo = i.IssueTo,
                   ReceviedBy = i.ReceviedBy,
                   Details = i.Details,
                   CreatedBy = i.CreatedBy
               }).FirstOrDefault();

            return new ViewAsPdf("Printing/PrintIE", Issue)
            {
                CustomSwitches = "--disable-smart-shrinking ",
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait

            };
        }
    }
}

Ledger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title> IT Ledger </title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
    <link href="css/styles.css" rel="stylesheet" />
    <link href="css/custom.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.1/css/dataTables.dataTables.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand ps-3" href="/">IT Ledger</a>
        
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" style="visibility:hidden;">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu" style="background: black;">

                    <div class="nav" >
                        
                        <a class="nav-link " asp-controller="dashboard" asp-action="index">
                            <div class="sb-nav-link-icon "><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                       
                        <a class="nav-link" asp-controller="equipment" asp-action="index">
                            <div class="sb-nav-link-icon"><i class="fas fa-database"></i></div>
                            Equipments
                        </a>
                        
                        <a class="nav-link" asp-controller="branch" asp-action="index">
                            <div class="sb-nav-link-icon"><i class="fas fa-code-branch"></i></div>
                            Branch
                        </a>


                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                            Issue Equipment
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="generalissue" asp-action="index"> 
                                    <span class="fas fa-chevron-right"></span> &nbsp; General Equipments</a>

                            </nav>
                        </div>


                          <a class="nav-link" asp-controller="Issue" asp-action="index">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>

                                </div>
                            Logout 
                        </a>

                      




                    </div>
                </div>

                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Aqib Sattar
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>


                @RenderBody()




            </main>
            <footer class="">
                <div class="container-fluid ">
                    <div class="d-flex align-items-center justify-content-between small">
                        <p style="padding: 15px; color: white;"> Ledger Software - Developed By IT Branch </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
   
    <!-- DataTables -->
    <script src="https://cdn.datatables.net/2.0.1/js/dataTables.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>




    <script src="js/custom.js"></script>
    <script src="js/datatables.js"></script>
</body>
</html>

@await RenderSectionAsync("Scripts", required: false)